import RuntimeContracts

/// machine-readable capability catalog（M0）。编辑器补全、AI 上下文、导入诊断与 docs/SWIFT_SUPPORT.md 共用。
///
/// 约定：
/// - supported：已实现，testIDs 指向真实存在的测试函数名或 `differential/<夹具>.swift`（测试校验）。
/// - partial：已实现但有限制（notes 说明）；可能尚无专门测试。
/// - unsupported：合法 Swift/SwiftUI，但使用时产生 unsupportedSyntax / unsupportedAPI 诊断并附带此 ID。
enum CapabilityCatalogData {
    static var catalog: CapabilityCatalog { CapabilityCatalog(runtimeVersion: SwiftRuntimeEngine.version, entries: entries) }

    static let v = RuntimeVersion(0, 1, 0)

    static func e(_ id: String, _ cat: CapabilityCategory, _ name: String, _ level: SupportLevel, sig: String? = nil,
                  tests: [String] = [], notes: String? = nil) -> CapabilityEntry {
        CapabilityEntry(id: id, category: cat, displayName: name, signature: sig, level: level, minRuntimeVersion: v,
                        testIDs: tests, notes: notes)
    }

    static func d(_ n: String) -> String { "differential/\(n).swift" }

    static let entries: [CapabilityEntry] = syntax + stdlib + propertyWrappers + views + modifiers

    // MARK: - 语法

    static let syntax: [CapabilityEntry] = [
        e("syntax.literal.int", .syntax, "整数字面量（十/十六/二进制、下划线）", .supported, tests: [d("01_int_arithmetic"), d("30_tuples_ternary_misc")]),
        e("syntax.literal.double", .syntax, "浮点字面量", .supported, tests: [d("02_double_arithmetic")]),
        e("syntax.literal.string", .syntax, "字符串字面量与转义", .supported, tests: [d("03_strings")]),
        e("syntax.literal.bool", .syntax, "布尔字面量", .supported, tests: [d("04_bool_logic")]),
        e("syntax.stringInterpolation", .syntax, "字符串插值 \\(x)", .supported, tests: [d("03_strings"), d("23_print_formatting")],
          notes: "不支持带参数的插值（如 \\(x, format:)）"),
        e("syntax.multilineString", .syntax, "多行字符串字面量", .supported, tests: [d("03_strings")]),
        e("syntax.let", .syntax, "let 常量", .supported, tests: [d("05_let_var_scope")]),
        e("syntax.var", .syntax, "var 变量", .supported, tests: [d("05_let_var_scope")]),
        e("syntax.typeAnnotation", .syntax, "类型标注", .supported, tests: [d("05_let_var_scope")],
          notes: "Int/Double/Bool/String/Character(按 String)/CGFloat(按 Double)/数组/字典/Optional/函数类型/元组/用户类型"),
        e("syntax.operator.arithmetic", .syntax, "算术运算 + - * / %", .supported, tests: [d("01_int_arithmetic"), d("02_double_arithmetic")],
          notes: "Int 溢出、除零为受控 runtimeTrap；Int 与 Double 不隐式转换（字面量按上下文定型）"),
        e("syntax.operator.comparison", .syntax, "比较运算", .supported, tests: [d("04_bool_logic")]),
        e("syntax.operator.logical", .syntax, "逻辑运算与短路 && || !", .supported, tests: [d("04_bool_logic")]),
        e("syntax.operator.compoundAssignment", .syntax, "复合赋值 += -= *= /= %= …", .supported, tests: [d("01_int_arithmetic")]),
        e("syntax.operator.bitwise", .syntax, "位运算 & | ^ << >> ~", .supported, tests: [d("01_int_arithmetic")]),
        e("syntax.operator.wrapping", .syntax, "溢出运算 &+ &- &*", .supported, tests: [d("01_int_arithmetic")]),
        e("syntax.operator.ternary", .syntax, "三元运算 ?:", .supported, tests: [d("30_tuples_ternary_misc")]),
        e("syntax.operator.nilCoalescing", .syntax, "空合运算 ??", .supported, tests: [d("21_optionals")]),
        e("syntax.range", .syntax, "区间 ..< 与 ...（双侧）与单侧区间", .supported, tests: [d("06_ranges_for"), d("36_w3_partial_range")],
          notes: "Int 区间；单侧（a[..<n]、a[n...]）支持构造、数组下标切片、打印与比较，for-in 单侧报错；Double 区间尚不支持"),
        e("syntax.if", .syntax, "if / else if / else", .supported, tests: [d("07_if_guard")]),
        e("syntax.guard", .syntax, "guard … else", .supported, tests: [d("07_if_guard")]),
        e("syntax.switch", .syntax, "switch（字面量、区间、多值、枚举 case、关联值模式、default）", .supported,
          tests: [d("08_switch_literals"), d("09_enums"), d("32_w3_enum_associated")],
          notes: "枚举/Bool 做穷尽性检查；不支持 fallthrough、元组模式"),
        e("syntax.switch.where", .syntax, "switch case 的 where 子句", .partial, tests: [d("08_switch_literals"), d("32_w3_enum_associated")]),
        e("syntax.switch.valueBinding", .syntax, "case let x / 关联值绑定", .partial, tests: [d("08_switch_literals"), d("32_w3_enum_associated")],
          notes: "支持绑定整个值与 .case(let x[, …])（含标签校验、字面量混合、case let 前缀）"),
        e("syntax.forIn", .syntax, "for-in（区间、数组、字典、字符串、stride）", .supported, tests: [d("06_ranges_for"), d("20_dictionaries")]),
        e("syntax.forIn.where", .syntax, "for-in where", .supported, tests: [d("06_ranges_for")]),
        e("syntax.forIn.tuplePattern", .syntax, "for (i, x) in … 元组解构", .partial, tests: [d("06_ranges_for"), d("20_dictionaries")],
          notes: "只在 for-in 中支持一层元组模式"),
        e("syntax.while", .syntax, "while / while let", .supported, tests: [d("10_while_repeat")]),
        e("syntax.repeatWhile", .syntax, "repeat-while", .supported, tests: [d("10_while_repeat")]),
        e("syntax.break", .syntax, "break", .supported, tests: [d("10_while_repeat")]),
        e("syntax.continue", .syntax, "continue", .supported, tests: [d("10_while_repeat")]),
        e("syntax.function", .syntax, "函数声明与返回值", .supported, tests: [d("11_functions")]),
        e("syntax.function.argumentLabels", .syntax, "参数标签与重载", .supported, tests: [d("11_functions")]),
        e("syntax.function.defaultArguments", .syntax, "默认参数值", .partial, tests: [d("11_functions")],
          notes: "静态解析的调用支持；嵌套函数与动态分派调用不支持默认值"),
        e("syntax.function.nested", .syntax, "嵌套函数", .supported, tests: [d("11_functions"), d("13_closures_capture")]),
        e("syntax.recursion", .syntax, "递归", .supported, tests: [d("12_recursion"), "deepRecursionStopsAtMaxCallDepth"]),
        e("syntax.functionReference", .syntax, "函数作为值（square、+、>、action: method）", .partial, tests: [d("11_functions"), d("14_closures_syntax")],
          notes: "支持顶层函数、运算符、无参实例方法引用；不支持带标签引用 f(x:)"),
        e("syntax.closure", .syntax, "闭包字面量", .supported, tests: [d("13_closures_capture"), d("14_closures_syntax")]),
        e("syntax.closure.trailing", .syntax, "尾随闭包", .supported, tests: [d("14_closures_syntax")]),
        e("syntax.closure.multipleTrailing", .syntax, "多个尾随闭包", .partial, notes: "用于 Button { } label: { } 等内建视图"),
        e("syntax.closure.shorthandArgs", .syntax, "$0 简写参数", .supported, tests: [d("14_closures_syntax")]),
        e("syntax.closure.captureByReference", .syntax, "按引用捕获 var / 按值捕获 let", .supported,
          tests: ["counterClosureCapturesVarByReference", "letCaptureIsByValueAndLoopBindingsAreFresh", d("13_closures_capture")]),
        e("syntax.struct", .syntax, "struct", .supported, tests: [d("15_struct_basics")]),
        e("syntax.struct.memberwiseInit", .syntax, "逐一成员构造器", .supported, tests: [d("15_struct_basics")]),
        e("syntax.struct.init", .syntax, "自定义 init", .supported, tests: [d("17_struct_init_static")], notes: "不检查确定初始化；不支持 self.init 委托"),
        e("syntax.struct.computedProperty", .syntax, "计算属性（只读）", .supported, tests: [d("15_struct_basics")]),
        e("syntax.struct.method", .syntax, "实例方法", .supported, tests: [d("15_struct_basics")]),
        e("syntax.struct.mutating", .syntax, "mutating 方法", .supported, tests: [d("15_struct_basics"), "mutatingMethodThroughStateAndNestedPaths"]),
        e("syntax.struct.static", .syntax, "static 属性与方法", .supported, tests: [d("17_struct_init_static")]),
        e("syntax.struct.valueSemantics", .syntax, "值语义复制", .supported, tests: ["structCopyIsIndependent", "arrayCopyIsIndependent", d("16_value_semantics")]),
        e("syntax.enum", .syntax, "enum（无关联值）", .supported, tests: [d("09_enums")]),
        e("syntax.enum.rawValue", .syntax, "enum 原始值（Int/String/Double）", .supported, tests: [d("09_enums")]),
        e("syntax.enum.caseIterable", .syntax, "CaseIterable.allCases", .supported, tests: [d("09_enums")]),
        e("syntax.enum.methods", .syntax, "enum 方法、计算属性、mutating", .supported, tests: [d("09_enums")]),
        e("syntax.extension", .syntax, "同模块 extension（方法、计算属性、init）", .supported, tests: [d("17_struct_init_static"), "allFileOrdersProduceSameScriptOutput"]),
        e("syntax.optional", .syntax, "Optional", .supported, tests: [d("21_optionals")], notes: "运行期扁平表示，嵌套可选（Int??）不区分"),
        e("syntax.optional.binding", .syntax, "if let / guard let / while let", .supported, tests: [d("07_if_guard"), d("21_optionals")]),
        e("syntax.optional.chaining", .syntax, "可选链 ?.", .supported, tests: [d("21_optionals"), d("16_value_semantics")]),
        e("syntax.optional.forceUnwrap", .syntax, "强制解包 !（nil 时受控 trap）", .supported, tests: [d("28_trap_force_unwrap_nil"), "runtimeTrapsBecomeDiagnostics"]),
        e("syntax.tuple", .syntax, "元组值、标签访问与解构声明", .partial,
          tests: [d("11_functions"), d("30_tuples_ternary_misc"), d("31_w3_tuple")],
          notes: "支持 let/var 解构声明（扁平一层，通配符 _ 可跳过）；不支持解构赋值"),
        e("syntax.keyPath", .syntax, "KeyPath \\.self / \\.prop", .partial, tests: ["forEachOverIdentifiableAndRange"], notes: "只用于 ForEach/List 的 id:"),
        e("syntax.topLevelCode", .syntax, "main.swift 顶层语句（脚本入口）", .supported, tests: ["scriptEntryPrintsToConsoleAndCompletes", "topLevelStatementsOutsideMainSwiftIsError"]),
        e("syntax.mainApp", .syntax, "@main App + WindowGroup", .partial, tests: ["counterViaMainAppEntry", "multipleMainAppsIsError"],
          notes: "只支持单个 WindowGroup { 根视图 }；App 内不能有存储属性"),
        e("syntax.import", .syntax, "import SwiftUI / Foundation", .partial, notes: "其他模块产生 unsupportedAPI"),
        e("syntax.accessControl", .syntax, "private / fileprivate 跨文件可见性", .partial,
          tests: ["crossFilePrivateMemberIsNameResolutionError", "crossFilePrivateFunctionIsNameResolutionError", "privateSetterBlocksCrossFileMutation"],
          notes: "private 与 fileprivate 都按\"仅本文件可见\"处理"),
        // 尚不支持
        e("syntax.class", .syntax, "class 与继承", .unsupported),
        e("syntax.protocol", .syntax, "自定义协议 / 其他协议遵循 / some·any 类型", .unsupported,
          notes: "可遵循：View、App、Identifiable、Hashable、Equatable、CaseIterable、CustomStringConvertible、Sendable"),
        e("syntax.generics", .syntax, "泛型", .unsupported),
        e("syntax.actor", .syntax, "actor", .unsupported),
        e("syntax.asyncAwait", .syntax, "async / await", .unsupported),
        e("syntax.errorHandling", .syntax, "throws / try / do-catch", .unsupported),
        e("syntax.macro", .syntax, "宏（@Observable、#Preview …）", .unsupported),
        e("syntax.attribute", .syntax, "@State/@Binding/@main/@ViewBuilder/@discardableResult 之外的属性", .unsupported),
        e("syntax.tuplePattern", .syntax, "元组解构声明", .partial, tests: [d("31_w3_tuple")],
          notes: "支持 let/var 解构声明（扁平一层）；不支持解构赋值、switch/if-case 元组模式"),
        e("syntax.typeCasting", .syntax, "as / as? / is", .unsupported),
        e("syntax.typealias", .syntax, "typealias", .unsupported),
        e("syntax.defer", .syntax, "defer", .unsupported),
        e("syntax.fallthrough", .syntax, "fallthrough", .unsupported),
        e("syntax.labeledStatement", .syntax, "带标签语句 / 带标签 break·continue", .unsupported),
        e("syntax.operatorDecl", .syntax, "自定义运算符 / 运算符函数", .unsupported),
        e("syntax.subscriptDecl", .syntax, "自定义 subscript", .unsupported),
        e("syntax.nestedType", .syntax, "嵌套类型 / 局部类型", .unsupported),
        e("syntax.ifExpression", .syntax, "if/switch 作为表达式", .unsupported),
        e("syntax.ifConfig", .syntax, "#if 条件编译", .unsupported),
        e("syntax.availability", .syntax, "#available", .unsupported),
        e("syntax.function.inout", .syntax, "inout 参数", .supported, tests: [d("34_w3_inout")],
          notes: "具名函数/方法/init 调用（copy-in/copy-out，&实参按地址回写）；函数值与动态分派调用不支持；同一变量多传不做独占检查"),
        e("syntax.function.variadic", .syntax, "可变参数", .unsupported),
        e("syntax.enum.associatedValues", .syntax, "带关联值的 enum", .supported, tests: [d("32_w3_enum_associated")],
          notes: "构造（显式 R.ok(…)/隐式 .ok(…)，标签校验）+ switch/if-case 模式匹配（含绑定、字面量、where）；带关联值的 case 无 allCases/rawValue"),
        e("syntax.struct.computedSetter", .syntax, "计算属性 setter", .supported, tests: [d("33_w3_setter_didset")],
          notes: "get/set（set 用 newValue，可自定义参数名）；静态计算属性 setter 不支持；计算属性上的 mutating 方法调用不支持"),
        e("syntax.struct.propertyObservers", .syntax, "didSet 属性观察器", .partial, tests: [d("33_w3_setter_didset")],
          notes: "存储属性/全局/static 的 didSet（赋值后触发一次，init 内不触发，自体钳制不递归）；mutating 方法整体写回与 $ 绑定写入不触发；willSet 忽略并警告"),
        e("syntax.struct.lazy", .syntax, "lazy 属性", .unsupported),
        e("syntax.struct.failableInit", .syntax, "init?", .unsupported),
        e("syntax.closure.captureList", .syntax, "闭包捕获列表 [x]", .unsupported),
        e("syntax.extension.stdlibType", .syntax, "扩展标准库/系统类型", .unsupported),
        e("syntax.globalComputed", .syntax, "全局/局部计算变量", .unsupported),
        e("syntax.implicitMemberCall", .syntax, "隐式成员调用 .foo(…)（如 .system(size:)）", .unsupported),
        e("syntax.declaration", .syntax, "其他声明", .unsupported),
        e("syntax.statement", .syntax, "其他语句", .unsupported),
        e("syntax.expression", .syntax, "其他表达式", .unsupported),
    ]

    // MARK: - 标准库

    /// (类型, 名称, 签名, 级别, 测试, 备注)
    static let stdlibTable: [(String, String, String, SupportLevel, [String], String?)] = [
        ("Array", "append", "append(_:) / append(contentsOf:)", .supported, [d("18_arrays")], nil),
        ("Array", "insert", "insert(_:at:)", .supported, [d("18_arrays")], nil),
        ("Array", "remove", "remove(at:)", .supported, [d("18_arrays")], "越界为受控 trap"),
        ("Array", "removeLast", "removeLast()", .supported, [d("18_arrays"), "runtimeTrapsBecomeDiagnostics"], nil),
        ("Array", "removeFirst", "removeFirst()", .supported, [d("18_arrays")], nil),
        ("Array", "removeAll", "removeAll() / removeAll(where:)", .supported, [d("18_arrays"), "forEachReorderKeepsRowStateWithItsID"], nil),
        ("Array", "popLast", "popLast()", .supported, [d("10_while_repeat")], nil),
        ("Array", "sort", "sort() / sort(by:)", .supported, [d("18_arrays")], nil),
        ("Array", "reverse", "reverse()", .supported, [d("18_arrays")], nil),
        ("Array", "swapAt", "swapAt(_:_:)", .supported, [d("18_arrays"), d("24_algorithms")], nil),
        ("Array", "contains", "contains(_:) / contains(where:)", .supported, [d("18_arrays"), d("19_array_higher_order")], nil),
        ("Array", "allSatisfy", "allSatisfy(_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "map", "map(_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "compactMap", "compactMap(_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "filter", "filter(_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "forEach", "forEach(_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "reduce", "reduce(_:_:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "sorted", "sorted() / sorted(by:)", .supported, [d("19_array_higher_order")], nil),
        ("Array", "reversed", "reversed()", .supported, [d("06_ranges_for"), d("18_arrays")], "返回数组"),
        ("Array", "enumerated", "enumerated()", .supported, [d("19_array_higher_order")], "返回 (offset:, element:) 数组"),
        ("Array", "first", "first / first(where:)", .supported, [d("18_arrays"), d("19_array_higher_order")], nil),
        ("Array", "last", "last", .supported, [d("18_arrays")], nil),
        ("Array", "firstIndex", "firstIndex(of:) / firstIndex(where:)", .supported, [d("18_arrays"), d("19_array_higher_order")], nil),
        ("Array", "lastIndex", "lastIndex(of:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "min", "min() / min(by:)", .supported, [d("18_arrays")], nil),
        ("Array", "max", "max() / max(by:)", .supported, [d("18_arrays")], nil),
        ("Array", "count", "count / count(where:)", .supported, [d("18_arrays")], nil),
        ("Array", "isEmpty", "isEmpty", .supported, [d("18_arrays")], nil),
        ("Array", "indices", "indices", .supported, [d("18_arrays")], nil),
        ("Array", "startIndex", "startIndex", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "endIndex", "endIndex", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "joined", "joined(separator:) / joined()", .supported, [d("03_strings"), d("24_algorithms")], "仅 [String]"),
        ("Array", "prefix", "prefix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "suffix", "suffix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "dropFirst", "dropFirst() / dropFirst(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "dropLast", "dropLast() / dropLast(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Array", "subscript", "a[i] / a[range]", .supported, [d("18_arrays"), d("27_trap_index_out_of_range")], "越界为受控 trap"),
        ("Array", "init", "Array(seq) / Array(repeating:count:) / [T]()", .supported, [d("18_arrays"), d("06_ranges_for")], nil),
        ("Range", "count", "count", .supported, [d("06_ranges_for")], nil),
        ("Range", "isEmpty", "isEmpty", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "lowerBound", "lowerBound", .supported, [d("06_ranges_for")], nil),
        ("Range", "upperBound", "upperBound", .supported, [d("06_ranges_for")], nil),
        ("Range", "first", "first", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "last", "last", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "contains", "contains(_:)", .supported, [d("06_ranges_for")], nil),
        ("Range", "map", "map(_:)", .supported, [d("12_recursion")], "序列方法：物化为数组（受 maxCollectionElements 约束）"),
        ("Range", "filter", "filter(_:)", .supported, [d("24_algorithms")], nil),
        ("Range", "reversed", "reversed()", .supported, [d("06_ranges_for")], nil),
        ("Range", "reduce", "reduce(_:_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "forEach", "forEach(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "allSatisfy", "allSatisfy(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "compactMap", "compactMap(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "sorted", "sorted()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "enumerated", "enumerated()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "firstIndex", "firstIndex(of:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "lastIndex", "lastIndex(of:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "min", "min()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "max", "max()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "joined", "joined()", .unsupported, [], "Int 元素序列无 joined（仅对 String 元素序列有意义）"),
        ("Range", "prefix", "prefix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "suffix", "suffix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "dropFirst", "dropFirst()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Range", "dropLast", "dropLast()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "count", "count", .supported, [d("03_strings")], "按字素簇计数"),
        ("String", "isEmpty", "isEmpty", .supported, [d("03_strings")], nil),
        ("String", "first", "first", .supported, [d("37_w4_stdlib_breadth")], "Character 以单字符 String 表示"),
        ("String", "last", "last", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "description", "description", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "uppercased", "uppercased()", .supported, [d("03_strings")], nil),
        ("String", "lowercased", "lowercased()", .supported, [d("03_strings")], nil),
        ("String", "contains", "contains(_:)", .supported, [d("03_strings")], nil),
        ("String", "hasPrefix", "hasPrefix(_:)", .supported, [d("03_strings")], nil),
        ("String", "hasSuffix", "hasSuffix(_:)", .supported, [d("03_strings")], nil),
        ("String", "append", "append(_:) / +=", .supported, [d("03_strings")], nil),
        ("String", "split", "split(separator:)", .supported, [d("03_strings")], "返回 [String]"),
        ("String", "components", "components(separatedBy:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "replacingOccurrences", "replacingOccurrences(of:with:)", .supported, [d("03_strings")], nil),
        ("String", "trimmingCharacters", "trimmingCharacters(in:)", .supported, [d("03_strings")], "只去除空白与换行"),
        ("String", "reversed", "reversed()", .supported, [d("03_strings")], nil),
        ("String", "prefix", "prefix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "suffix", "suffix(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "dropFirst", "dropFirst()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "dropLast", "dropLast()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "removeAll", "removeAll()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "removeLast", "removeLast()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "removeFirst", "removeFirst()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "filter", "filter(_:)", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "map", "map(_:)", .supported, [d("37_w4_stdlib_breadth")], "返回 [String]（Character 以单字符 String 表示）"),
        ("String", "sorted", "sorted()", .supported, [d("37_w4_stdlib_breadth")], "返回 [String]（按字符排序）"),
        ("String", "enumerated", "enumerated()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("String", "init", "String(x) / String(describing:) / String(repeating:count:)", .supported, [d("03_strings"), d("22_conversions")], nil),
        ("String", "subscript", "s[i]（String.Index）", .unsupported, [], nil),
        ("Dictionary", "subscript", "d[k] / d[k, default:]", .supported, [d("20_dictionaries"), d("29_trap_missing_dict_key")], "赋 nil 删除键"),
        ("Dictionary", "count", "count", .supported, [d("20_dictionaries")], nil),
        ("Dictionary", "isEmpty", "isEmpty", .supported, [d("20_dictionaries")], nil),
        ("Dictionary", "keys", "keys", .supported, [d("20_dictionaries")], "返回数组；遍历顺序为插入顺序（Swift 原生顺序不确定）"),
        ("Dictionary", "values", "values", .supported, [d("20_dictionaries")], nil),
        ("Dictionary", "removeValue", "removeValue(forKey:)", .supported, [d("20_dictionaries")], nil),
        ("Dictionary", "updateValue", "updateValue(_:forKey:)", .supported, ["dictionarySequenceOps"], nil),
        ("Dictionary", "removeAll", "removeAll()", .supported, ["dictionarySequenceOps"], nil),
        ("Dictionary", "mapValues", "mapValues(_:)", .supported, ["dictionarySequenceOps"], "插入顺序保留"),
        ("Dictionary", "filter", "filter(_:)", .supported, ["dictionarySequenceOps"], "插入顺序保留"),
        ("Dictionary", "sorted", "sorted(by:)", .supported, [d("20_dictionaries")], "元素为 (key:, value:) 元组"),
        ("Dictionary", "map", "map(_:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "forEach", "forEach(_:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "reduce", "reduce(_:_:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "contains", "contains(where:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "first", "first(where:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "compactMap", "compactMap(_:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "allSatisfy", "allSatisfy(_:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "min", "min(by:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Dictionary", "max", "max(by:)", .supported, ["dictionarySequenceOps"], "元素为 (key:, value:) 元组"),
        ("Int", "init", "Int(String) → Int? / Int(Double)", .supported, [d("22_conversions")], "Int(Double) 对 NaN/无穷/越界为受控 trap"),
        ("Int", "isMultiple", "isMultiple(of:)", .supported, [d("01_int_arithmetic")], nil),
        ("Int", "signum", "signum()", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Int", "description", "description", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Int", "magnitude", "magnitude", .supported, [d("37_w4_stdlib_breadth")], "UInt 语义，按 Int 非负值表示"),
        ("Double", "init", "Double(Int) / Double(String) → Double?", .supported, [d("22_conversions"), d("02_double_arithmetic")], nil),
        ("Double", "rounded", "rounded() / rounded(_:)", .supported, [d("02_double_arithmetic"), d("37_w4_stdlib_breadth")], "规则：up/down/toNearestOrAwayFromZero/toNearestOrEven"),
        ("Double", "squareRoot", "squareRoot()", .supported, [d("02_double_arithmetic")], nil),
        ("Double", "truncatingRemainder", "truncatingRemainder(dividingBy:)", .supported, [d("02_double_arithmetic")], nil),
        ("Double", "description", "description", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Double", "isNaN", "isNaN", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Double", "isInfinite", "isInfinite", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Double", "isFinite", "isFinite", .supported, [d("37_w4_stdlib_breadth")], nil),
        ("Bool", "toggle", "toggle()", .supported, [d("04_bool_logic")], nil),
        ("Bool", "description", "description", .supported, [d("37_w4_stdlib_breadth")], nil),
    ]

    static let stdlibMembers: [CapabilityEntry] = stdlibTable.map { (row: (String, String, String, SupportLevel, [String], String?)) -> CapabilityEntry in
        e("stdlib.\(row.0).\(row.1)", .stdlib, "\(row.0).\(row.1)", row.3, sig: row.2, tests: row.4, notes: row.5)
    }

    static let stdlibUnsupported: [CapabilityEntry] = {
        var out: [CapabilityEntry] = knownUnsupportedTypes.subtracting(unsupportedViewNames).sorted().map { (n: String) -> CapabilityEntry in
            e("stdlib.\(n)", .stdlib, n, .unsupported)
        }
        out += knownUnsupportedFunctions.sorted().map { (n: String) -> CapabilityEntry in e("stdlib.\(n)", .stdlib, "\(n)(…)", .unsupported) }
        out += ["Int", "Double", "Bool", "String", "Array"].map { (n: String) -> CapabilityEntry in
            e("stdlib.\(n).random", .stdlib, "\(n).random…", .unsupported, notes: "非确定性 API")
        }
        out.append(e("stdlib.Bool.init", .stdlib, "Bool(…)", .unsupported))
        out.append(e("stdlib.Character.init", .stdlib, "Character(…)", .unsupported))
        return out
    }()

    static let stdlib: [CapabilityEntry] = stdlibMembers + stdlibFunctions + stdlibUnsupported

    static let stdlibFunctions: [CapabilityEntry] = [
        e("stdlib.print", .stdlib, "print", .supported, sig: "print(_:..., separator:terminator:)", tests: [d("23_print_formatting")],
          notes: "输出为 .console(.stdout, …) 事件；格式与 Swift description/debugDescription 一致"),
        e("stdlib.String.format", .stdlib, "String(format:)", .supported, sig: "String(format:_:...)（仅 %.Nf 与 %%)",
          tests: [d("35_w3_format_date"), "stringFormatIntArgActsAsDouble"],
          notes: "Int 实参按 Double 格式化（Swift 原生要求 Double）；其他占位符报 unsupportedAPI"),
        e("stdlib.Date", .stdlib, "Date", .supported, sig: "Date() / Date.now（只读）", tests: [d("35_w3_format_date")],
          notes: "只读基础：description/打印/==/</比较；无运算与格式化器；时钟读取是允许的非确定性（随机/网络仍一律拒绝）"),
        e("stdlib.abs", .stdlib, "abs", .supported, sig: "abs(_:)", tests: [d("01_int_arithmetic"), d("22_conversions")]),
        e("stdlib.min", .stdlib, "min", .supported, sig: "min(_:_:...)", tests: [d("01_int_arithmetic")]),
        e("stdlib.max", .stdlib, "max", .supported, sig: "max(_:_:...)", tests: [d("22_conversions")]),
        e("stdlib.stride", .stdlib, "stride", .supported, sig: "stride(from:to:by:) / stride(from:through:by:)", tests: [d("06_ranges_for")],
          notes: "物化为数组"),
        e("stdlib.fatalError", .stdlib, "fatalError", .supported, sig: "fatalError(_:)", tests: ["runtimeTrapsBecomeDiagnostics"], notes: "作为受控 runtimeTrap（终止运行，非进程崩溃）"),
        e("stdlib.precondition", .stdlib, "precondition", .supported, sig: "precondition(_:_:)", tests: ["runtimeTrapsBecomeDiagnostics"], notes: "作为受控 runtimeTrap"),
        e("stdlib.assert", .stdlib, "assert", .supported, sig: "assert(_:_:)", tests: ["runtimeTrapsBecomeDiagnostics"], notes: "作为受控 runtimeTrap"),
        e("stdlib.math", .stdlib, "sqrt/floor/ceil/round/sin/cos/exp/log/pow", .supported, tests: [d("37_w4_stdlib_breadth")], notes: "Foundation 函数，仅 Double"),
        e("stdlib.zip", .stdlib, "zip", .supported, sig: "zip(_:_:)", tests: [d("37_w4_stdlib_breadth")], notes: "物化为 (0:, 1:) 元组数组，长度取较短序列"),
        e("stdlib.repeatElement", .stdlib, "repeatElement", .supported, sig: "repeatElement(_:count:)", tests: [d("37_w4_stdlib_breadth")], notes: "物化为数组"),
        e("stdlib.CGFloat", .stdlib, "CGFloat", .partial, notes: "按 Double 处理"),
        e("stdlib.Character", .stdlib, "Character", .partial, notes: "按单字符 String 处理"),
    ]

    // MARK: - 属性包装器

    static let propertyWrappers: [CapabilityEntry] = [
        e("propertyWrapper.State", .propertyWrapper, "@State", .supported,
          tests: ["counterRootViewRendersAndIncrementsOnAction", "forEachReorderKeepsRowStateWithItsID", "bindingPassedToChildWritesParentState"],
          notes: "键 = 视图身份路径 + 字段名；视图重建不重新初始化；视图离开层级后丢弃"),
        e("propertyWrapper.Binding", .propertyWrapper, "@Binding", .supported, tests: ["bindingPassedToChildWritesParentState"]),
        e("propertyWrapper.Binding.projection", .propertyWrapper, "$state / $state.field / $array[i]", .supported,
          tests: ["textFieldSetBindingWritesBack", "bindingPassedToChildWritesParentState"]),
    ] + knownPropertyWrappers.sorted().map { e("propertyWrapper.\($0)", .propertyWrapper, "@\($0)", .unsupported) }

    // MARK: - 视图

    static let views: [CapabilityEntry] = [
        e("view.Text", .view, "Text", .supported, sig: "Text(_: String)", tests: ["counterRootViewRendersAndIncrementsOnAction"]),
        e("view.Button", .view, "Button", .supported, sig: "Button(_:action:) / Button(action:label:) / Button(_:role:action:)",
          tests: ["counterRootViewRendersAndIncrementsOnAction", "closureEscapesIntoButtonAndMutatesState"]),
        e("view.VStack", .view, "VStack", .supported, sig: "VStack(alignment:spacing:content:)", tests: ["counterRootViewRendersAndIncrementsOnAction"]),
        e("view.HStack", .view, "HStack", .supported, sig: "HStack(alignment:spacing:content:)", tests: ["counterRootViewRendersAndIncrementsOnAction"]),
        e("view.ZStack", .view, "ZStack", .supported, sig: "ZStack(alignment:content:)", tests: ["modifiersMapToRenderModifiers"]),
        e("view.Spacer", .view, "Spacer", .supported, sig: "Spacer(minLength:)", tests: ["modifiersMapToRenderModifiers"]),
        e("view.Divider", .view, "Divider", .supported, tests: ["forEachReorderKeepsRowStateWithItsID"]),
        e("view.TextField", .view, "TextField", .supported, sig: "TextField(_:text:)", tests: ["textFieldSetBindingWritesBack"]),
        e("view.SecureField", .view, "SecureField", .partial, sig: "SecureField(_:text:)"),
        e("view.Toggle", .view, "Toggle", .supported, sig: "Toggle(_:isOn:) / Toggle(isOn:label:)", tests: ["textFieldSetBindingWritesBack"]),
        e("view.ForEach", .view, "ForEach", .supported, sig: "ForEach(data, id: \\.self | \\.prop) { … } / ForEach(identifiable) / ForEach(range)",
          tests: ["forEachReorderKeepsRowStateWithItsID", "forEachOverIdentifiableAndRange"], notes: "行身份 = 稳定 id"),
        e("view.List", .view, "List", .supported, sig: "List { … } / List(data, id:) { … }", tests: ["conditionalBranchesAndOnAppear"]),
        e("view.NavigationStack", .view, "NavigationStack", .supported, sig: "NavigationStack { … } / NavigationStack(path: $path) { … }",
          tests: ["conditionalBranchesAndOnAppear", "navigationPushPopUnbound", "navigationPathBinding", "navigationDestinationLinkForm"],
          notes: "path 绑定支持 [String] 子集；目标 for: 只支持 String/Int；navigationDestination 须写在栈内容内部"),
        e("view.ScrollView", .view, "ScrollView", .supported, sig: "ScrollView([.vertical|.horizontal]) { … }",
          tests: ["w3ContainersRender"], notes: "轴向透传；showsIndicators: 形式尚不支持"),
        e("view.Group", .view, "Group", .supported, tests: ["w3ContainersRender"]),
        e("view.Form", .view, "Form", .supported, tests: ["w3ControlsRender"]),
        e("view.Section", .view, "Section", .supported, sig: "Section([header][footer:]) { … }（字符串）", tests: ["w3ControlsRender"],
          notes: "header/footer 只支持字符串"),
        e("view.Image", .view, "Image(systemName:)", .supported, sig: "Image(systemName:) / Image(_:)",
          tests: ["w3ControlsRender"], notes: "SF Symbols 名称透传；Image(\"resource\") 显示占位（M1 接入项目资源）"),
        e("view.Slider", .view, "Slider", .supported, sig: "Slider(value:in:[step:])",
          tests: ["sliderBindingWritesBack"],
          notes: "value 需 Binding<Double>（VM 双向绑定）；in: 为 Int 闭区间；标签暂不显示"),
        e("view.Stepper", .view, "Stepper", .supported, sig: "Stepper(_:value:[in:])",
          tests: ["stepperRendersLabelAndBounds"],
          notes: "value 需 Binding<Int>；step:/onIncrement 形式尚不支持"),
        e("view.Picker", .view, "Picker", .supported, sig: "Picker(_:selection:content:)",
          tests: ["pickerOptionsAndSelection"],
          notes: "selection 需 Binding（String/Int 等可传输类型）；内容为 ForEach/静态 Text 行（每行需 .tag）；样式见 modifier.pickerStyle"),
        e("view.NavigationLink", .view, "NavigationLink", .supported,
          sig: "NavigationLink(_:value:)/NavigationLink(value:label:)/NavigationLink(_:destination:)",
          tests: ["navigationPushPopUnbound", "navigationPathBinding", "navigationDestinationLinkForm"],
          notes: "value 只支持 String/Int；destination 形式按稳定链接 id 注册"),
        e("view.ProgressView", .view, "ProgressView", .partial),
        e("view.EmptyView", .view, "EmptyView", .partial),
        e("view.Color", .view, "Color.red / Color(red:green:blue:)", .partial, tests: ["modifiersMapToRenderModifiers"], notes: "只作为修饰符参数使用，不能作为视图"),
        e("view.customView", .view, "自定义 View（struct X: View）", .supported,
          tests: ["counterRootViewRendersAndIncrementsOnAction", "shuffledFileOrderProducesSameRenderTree"]),
        e("view.ViewBuilder", .view, "@ViewBuilder 语句序列与局部 let", .supported, tests: ["closureEscapesIntoButtonAndMutatesState"],
          notes: "专门支持，不是通用 result builder；不支持 for 循环（请用 ForEach）"),
        e("view.ViewBuilder.if", .view, "@ViewBuilder 中的 if / else / if let", .supported, tests: ["conditionalBranchesAndOnAppear", "textFieldSetBindingWritesBack"]),
        e("view.ViewBuilder.switch", .view, "@ViewBuilder 中的 switch", .partial),
    ] + unsupportedViewNames.sorted().map { e("view.\($0)", .view, $0, .unsupported) }

    // MARK: - 修饰符

    static let modifiers: [CapabilityEntry] = [
        e("modifier.padding", .modifier, "padding", .supported, sig: "padding() / padding(_: CGFloat) / padding(_: Edge.Set, _: CGFloat?)",
          tests: ["counterRootViewRendersAndIncrementsOnAction", "modifiersMapToRenderModifiers"]),
        e("modifier.font", .modifier, "font", .supported, sig: "font(_: Font.TextStyle)", tests: ["counterRootViewRendersAndIncrementsOnAction"],
          notes: "只支持文本样式（.title/.body…）"),
        e("modifier.fontWeight", .modifier, "fontWeight", .partial, sig: "fontWeight(_:)"),
        e("modifier.bold", .modifier, "bold", .supported, sig: "bold()", tests: ["modifiersMapToRenderModifiers"]),
        e("modifier.italic", .modifier, "italic", .partial, sig: "italic()"),
        e("modifier.foregroundColor", .modifier, "foregroundColor", .supported, sig: "foregroundColor(_: Color)", tests: ["modifiersMapToRenderModifiers"]),
        e("modifier.foregroundStyle", .modifier, "foregroundStyle", .supported, sig: "foregroundStyle(_: Color)", tests: ["modifiersMapToRenderModifiers"],
          notes: "映射为 RenderModifier.foregroundColor；只支持颜色"),
        e("modifier.tint", .modifier, "tint", .partial, notes: "映射为 foregroundColor"),
        e("modifier.background", .modifier, "background", .supported, sig: "background(_: Color)", tests: ["modifiersMapToRenderModifiers"], notes: "只支持颜色"),
        e("modifier.frame", .modifier, "frame", .supported, sig: "frame(width:height:maxWidth:maxHeight:alignment:)（有序子集）", tests: ["modifiersMapToRenderModifiers"]),
        e("modifier.cornerRadius", .modifier, "cornerRadius", .supported, tests: ["modifiersMapToRenderModifiers"]),
        e("modifier.opacity", .modifier, "opacity", .supported, tests: ["modifiersMapToRenderModifiers"]),
        e("modifier.disabled", .modifier, "disabled", .supported, tests: ["counterRootViewRendersAndIncrementsOnAction"]),
        e("modifier.hidden", .modifier, "hidden", .partial),
        e("modifier.navigationTitle", .modifier, "navigationTitle", .supported, sig: "navigationTitle(_: String)", tests: ["conditionalBranchesAndOnAppear"]),
        e("modifier.buttonStyle", .modifier, "buttonStyle", .supported, sig: "buttonStyle(.bordered | .borderedProminent | .plain | .borderless)",
          tests: ["counterRootViewRendersAndIncrementsOnAction"]),
        e("modifier.textFieldStyle", .modifier, "textFieldStyle", .partial),
        e("modifier.listStyle", .modifier, "listStyle", .partial),
        e("modifier.multilineTextAlignment", .modifier, "multilineTextAlignment", .partial),
        e("modifier.lineLimit", .modifier, "lineLimit", .partial),
        e("modifier.accessibilityLabel", .modifier, "accessibilityLabel", .partial),
        e("modifier.tag", .modifier, "tag", .partial),
        e("modifier.onAppear", .modifier, "onAppear", .partial, sig: "onAppear(perform:)", tests: ["conditionalBranchesAndOnAppear"],
          notes: "映射为 ActionID；由宿主发送 .appear(NodeID) 或 .action(ActionID) 触发，运行时不自动触发"),
        e("modifier.onDisappear", .modifier, "onDisappear", .partial, notes: "同 onAppear"),
        e("modifier.task", .modifier, "task", .partial, tests: ["taskRunsSyncBodyOnce"],
          notes: "同步子集：与 onAppear 同机制（宿主触发，不自动执行）；体内 await 按同步执行，不支持取消"),
        e("modifier.navigationDestination", .modifier, "navigationDestination", .supported,
          sig: ".navigationDestination(for: String.self/Int.self) { value in … }", tests: ["navigationPathBinding"],
          notes: "B-2：for: 仅 String/Int；须写在栈内容内部（先于目标解析完成注册）"),
        e("modifier.sheet", .modifier, "sheet", .supported, sig: ".sheet(isPresented:onDismiss:content:)",
          tests: ["sheetPresentDismiss"],
          notes: "B-3：isPresented Binding<Bool> + 内容闭包（捕获 state 读写直达）；手势关闭回传 .action(dismiss) 写 false 并跑 onDismiss；.dismissSheet 强制关闭不触发 onDismiss"),
        e("modifier.alert", .modifier, "alert", .supported, sig: ".alert(_:isPresented:actions:message:)",
          tests: ["alertButtonsAndAutoDismiss"],
          notes: "B-4：标题 + Binding<Bool> + 一到两个 Button + 可选消息；每个按钮保证 action，点击后自动关闭"),
        e("modifier.pickerStyle", .modifier, "pickerStyle", .supported, sig: ".pickerStyle(.segmented/.menu/.automatic)",
          tests: ["pickerOptionsAndSelection"], notes: "样式透传（接受并通过，桥接按默认样式渲染）"),
    ] + unsupportedModifierNames.map { e("modifier.\($0)", .modifier, $0, .unsupported) }

    static let unsupportedModifierNames = [
        "shadow", "overlay", "border", "clipShape", "onTapGesture", "gesture", "animation", "transition", "offset",
        "scaleEffect", "rotationEffect", "toolbar", "onChange", "onSubmit", "searchable", "refreshable", "swipeActions", "contextMenu",
        "environment", "environmentObject", "ignoresSafeArea", "fixedSize", "layoutPriority", "zIndex", "fill", "stroke", "resizable",
        "scaledToFit", "aspectRatio", "keyboardType", "focused", "fullScreenCover", "confirmationDialog",
        "labelStyle", "toggleStyle", "tabItem", "navigationBarTitleDisplayMode",
    ]
}
